// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Animal Farm",
    url: "./assets/animal-farm.gif",
    originalPrice: 19.99,
    salePrice: 9.99,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Fahrenheit 451",
    url: "./assets/Fahrenheit451Cover.jpg",
    originalPrice: 8.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Clockwork Orange",
    url: "./assets/clock.jpg",
    originalPrice: 14.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Lord of the Flies",
    url: "./assets/Lordfly.jpg",
    originalPrice: 13.99,
    salePrice: 7.99,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The Black Farm",
    url: "./assets/blackfarm.jpg",
    originalPrice: 12.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "N0S4A2",
    url: "./assets/nos4a2-joe-hill-book-cover.jpg",
    originalPrice: 19.99,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "Tender is the Flesh",
    url: "./assets/tender.jpg",
    originalPrice: 15,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Nightmare Girl",
    url: "./assets/nightmare-girl.jpg",
    originalPrice: 21.99,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Last House on Needless Street",
    url: "./assets/needless.jpg",
    originalPrice: 25,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Off The Deep End",
    url: "./assets/deepend.jpg",
    originalPrice: 14.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "The Only Good Indians",
    url: "./assets/indians.jpg",
    originalPrice: 25,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "No Longer Human",
    url: "./assets/nohuman.jpg",
    originalPrice: 17.99,
    salePrice: 12.95,
    rating: 4.5,
  },
];