// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Animal Farm",
    url: "https://cdnb.artstation.com/p/assets/images/images/015/140/301/original/sascha-sendlbeck-book-animation.gif?1547203918",
    originalPrice: 19.99,
    salePrice: 9.99,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Fahrenheit 451",
    url: "https://pepboatella.com/wp-content/uploads/2018/12/4.jpg",
    originalPrice: 8.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Clockwork Orange",
    url: "https://thebobsphere.files.wordpress.com/2018/09/cover-clockwork.png",
    originalPrice: 14.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Lord of the Flies",
    url: "./assets/Lordfly.jpg",
    originalPrice: 13.99,
    salePrice: 7.99,
    rating: 4.5,
  },
  {
    id: 5,
    title: "The Black Farm",
    url: "https://m.media-amazon.com/images/I/51D0fYTXxxL.jpg",
    originalPrice: 12.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "N0S4A2",
    url: "https://cdn11.bigcommerce.com/s-65f8qukrjx/images/stencil/800w/products/6175/17032/Hill_N0S4A2_cover__57881.1687451115.jpg?c=1",
    originalPrice: 19.99,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "Tender is the Flesh",
    url: "./assets/tender.jpg",
    originalPrice: 15,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Nightmare Girl",
    url: "./assets/nightmare-girl.jpg",
    originalPrice: 21.99,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Last House on Needless Street",
    url: "./assets/needless.jpg",
    originalPrice: 25,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Off The Deep End",
    url: "./assets/deepend.jpg",
    originalPrice: 14.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "The Only Good Indians",
    url: "./assets/indians.jpg",
    originalPrice: 25,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "No Longer Human",
    url: "./assets/nohuman.jpg",
    originalPrice: 17.99,
    salePrice: 12.95,
    rating: 4.5,
  },
];